
export interface DeGiroProduct {
    id: string                  // id: '19750059',
    name: string                // name: 'American Electric Power Company Inc',
    isin: string                // isin: 'US0255371017',
    symbol: string              // symbol: 'AEP',
    contractSize: number        // contractSize: 1,
    productType: string         // productType: 'STOCK',
    productTypeId: number       // productTypeId: 1,
    tradable: boolean           // tradable: true,
    category: string            // category: 'D',
    currency: string            // currency: 'EUR',
    active: boolean             // active: true,
    exchangeId: string          // exchangeId: '196',
    onlyEodPrices: boolean      // onlyEodPrices: false,
    orderTimeTypes: []          // orderTimeTypes: [ 'DAY', 'GTC' ],
    buyOrderTypes: []           // buyOrderTypes: [ 'LIMIT', 'MARKET', 'STOPLOSS', 'STOPLIMIT' ],
    sellOrderTypes: []          // sellOrderTypes: [ 'LIMIT', 'MARKET', 'STOPLOSS', 'STOPLIMIT' ],
    productBitTypes: []         // productBitTypes: [ 'US_RAS_GREEN_LIST' ],
    closePrice: number          // closePrice: 88.91,
    closePriceDate: string      // closePriceDate: '2022-10-31',
    feedQuality: string         // feedQuality: 'R',
    orderBookDepth: number      // orderBookDepth: 0,
    vwdIdentifierType: string   // vwdIdentifierType: 'vwdkey',
    vwdId: string               // vwdId: 'US0255371017.TRADE,E',
    qualitySwitchable: boolean  // qualitySwitchable: false,
    qualitySwitchFree: boolean  // qualitySwitchFree: false,
    vwdModuleId: number         // vwdModuleId: 34
}